### ISSUE TITLE
Oneshot should remember value of input parameters

### ISSUE THREAD

**Issue by filip-jezek** [creative-connections/Bodylight-Editor#37]
As of now, only one change is applied and the rest is defaulted - see https://filip-jezek.github.io/Ascites/#ascites.md - try having tips AND diffrerent inflow

**Comment by TomasKulhanek** [comment]
Seems to be rather feature request than a bug. A value is sent to model. When a new value is send - the model is reset, thus all parameter values are set to default and new value is set. No memory is implemented.

**Comment by TomasKulhanek** [comment]
FIX creative-connections/Bodylight-Editor#37 remember all values changed 16db9d0
